lib/generic_web/router.ex
defmodule GenericWeb.Router do
  use GenericWeb, :router

  import GenericWeb.UsersAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_users
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", GenericWeb do
    pipe_through :browser

    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", GenericWeb do
  #   pipe_through :api
  # end

  scope "/" do
    pipe_through :api
    forward "/api", Absinthe.Plug, schema: GenericWeb.Schema

    forward "/graphiql", Absinthe.Plug.GraphiQL,
      schema: GenericWeb.Schema,
      interface: :simple
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: GenericWeb.Telemetry
    end
  end

  ## Authentication routes

  scope "/", GenericWeb do
    pipe_through [:browser, :redirect_if_users_is_authenticated]

    get "/user/register", UsersRegistrationController, :new
    post "/user/register", UsersRegistrationController, :create
    get "/user/login", UsersSessionController, :new
    post "/user/login", UsersSessionController, :create
    get "/user/reset_password", UsersResetPasswordController, :new
    post "/user/reset_password", UsersResetPasswordController, :create
    get "/user/reset_password/:token", UsersResetPasswordController, :edit
    put "/user/reset_password/:token", UsersResetPasswordController, :update
  end

  scope "/", GenericWeb do
    pipe_through [:browser, :require_authenticated_users]

    delete "/user/logout", UsersSessionController, :delete
    get "/user/settings", UsersSettingsController, :edit
    put "/user/settings/update_password", UsersSettingsController, :update_password
    put "/user/settings/update_email", UsersSettingsController, :update_email
    get "/user/settings/confirm_email/:token", UsersSettingsController, :confirm_email
  end

  scope "/", GenericWeb do
    pipe_through [:browser]

    get "/user/confirm", UsersConfirmationController, :new
    post "/user/confirm", UsersConfirmationController, :create
    get "/user/confirm/:token", UsersConfirmationController, :confirm
  end
end

lib/generic_web/views/layout_view.ex
defmodule GenericWeb.LayoutView do
  use GenericWeb, :view
end

lib/generic_web/templates/layout/_users_menu.html.eex
<ul>
<%= if @current_users do %>
  <li><%= @current_users.email %></li>
  <li><%= link "Settings", to: Routes.users_settings_path(@conn, :edit) %></li>
  <li><%= link "Logout", to: Routes.users_session_path(@conn, :delete), method: :delete %></li>
<% else %>
  <li><%= link "Register", to: Routes.users_registration_path(@conn, :new) %></li>
  <li><%= link "Login", to: Routes.users_session_path(@conn, :new) %></li>
<% end %>
</ul>

lib/generic_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Generic · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <%= render "_users_menu.html", assigns %>
    <header>
      <section class="container">
        <nav role="navigation">
          <ul>
            <li><a href="https://hexdocs.pm/phoenix/overview.html">Get Started</a></li>
            <%= if function_exported?(Routes, :live_dashboard_path, 2) do %>
              <li><%= link "LiveDashboard", to: Routes.live_dashboard_path(@conn, :home) %></li>
            <% end %>
          </ul>
        </nav>
        <a href="https://phoenixframework.org/" class="phx-logo">
          <img src="<%= Routes.static_path(@conn, "/images/phoenix.png") %>" alt="Phoenix Framework Logo"/>
        </a>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= @inner_content %>
    </main>
  </body>
</html>