lib/generic_web/router.ex
defmodule GenericWeb.Router do
  use GenericWeb, :router

  import GenericWeb.UsersAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_users
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", GenericWeb do
    pipe_through :browser

    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", GenericWeb do
  #   pipe_through :api
  # end

  scope "/" do
    pipe_through :api
    forward "/api", Absinthe.Plug, schema: GenericWeb.Schema

    forward "/graphiql", Absinthe.Plug.GraphiQL,
      schema: GenericWeb.Schema,
      interface: :simple
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: GenericWeb.Telemetry
    end
  end

  ## Authentication routes

  scope "/", GenericWeb do
    pipe_through [:browser, :redirect_if_users_is_authenticated]

    get "/user/register", UsersRegistrationController, :new
    post "/user/register", UsersRegistrationController, :create
    get "/user/login", UsersSessionController, :new
    post "/user/login", UsersSessionController, :create
    get "/user/reset_password", UsersResetPasswordController, :new
    post "/user/reset_password", UsersResetPasswordController, :create
    get "/user/reset_password/:token", UsersResetPasswordController, :edit
    put "/user/reset_password/:token", UsersResetPasswordController, :update
  end

  scope "/", GenericWeb do
    pipe_through [:browser, :require_authenticated_users]

    delete "/user/logout", UsersSessionController, :delete
    get "/user/settings", UsersSettingsController, :edit
    put "/user/settings/update_password", UsersSettingsController, :update_password
    put "/user/settings/update_email", UsersSettingsController, :update_email
    get "/user/settings/confirm_email/:token", UsersSettingsController, :confirm_email
  end

  scope "/", GenericWeb do
    pipe_through [:browser]

    get "/user/confirm", UsersConfirmationController, :new
    post "/user/confirm", UsersConfirmationController, :create
    get "/user/confirm/:token", UsersConfirmationController, :confirm
  end
end

lib/generic_web/controllers/users_reset_password_controller.ex
defmodule GenericWeb.UsersResetPasswordController do
  use GenericWeb, :controller

  alias Generic.Accounts

  plug :get_users_by_reset_password_token when action in [:edit, :update]

  def new(conn, _params) do
    render(conn, "new.html")
  end

  def create(conn, %{"users" => %{"email" => email}}) do
    if users = Accounts.get_users_by_email(email) do
      Accounts.deliver_users_reset_password_instructions(
        users,
        &Routes.users_reset_password_url(conn, :edit, &1)
      )
    end

    # Regardless of the outcome, show an impartial success/error message.
    conn
    |> put_flash(
      :info,
      "If your e-mail is in our system, you will receive instructions to reset your password shortly."
    )
    |> redirect(to: "/")
  end

  def edit(conn, _params) do
    render(conn, "edit.html", changeset: Accounts.change_users_password(conn.assigns.users))
  end

  # Do not login the users after reset password to avoid a
  # leaked token giving the users access to the account.
  def update(conn, %{"users" => users_params}) do
    case Accounts.reset_users_password(conn.assigns.users, users_params) do
      {:ok, _} ->
        conn
        |> put_flash(:info, "Password reset successfully.")
        |> redirect(to: Routes.users_session_path(conn, :new))

      {:error, changeset} ->
        render(conn, "edit.html", changeset: changeset)
    end
  end

  defp get_users_by_reset_password_token(conn, _opts) do
    %{"token" => token} = conn.params

    if users = Accounts.get_users_by_reset_password_token(token) do
      conn |> assign(:users, users) |> assign(:token, token)
    else
      conn
      |> put_flash(:error, "Reset password link is invalid or it has expired.")
      |> redirect(to: "/")
      |> halt()
    end
  end
end

lib/generic_web/views/users_reset_password_view.ex
defmodule GenericWeb.UsersResetPasswordView do
  use GenericWeb, :view
end

lib/generic_web/templates/users_reset_password/edit.html.eex
<h1>Reset password</h1>

<%= form_for @changeset, Routes.users_reset_password_path(@conn, :update, @token), fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :password, "New password" %>
  <%= password_input f, :password, required: true %>
  <%= error_tag f, :password %>

  <%= label f, :password_confirmation, "Confirm new password" %>
  <%= password_input f, :password_confirmation, required: true %>
  <%= error_tag f, :password_confirmation %>

  <div>
    <%= submit "Reset password" %>
  </div>
<% end %>

<p>
  <%= link "Register", to: Routes.users_registration_path(@conn, :new) %> |
  <%= link "Login", to: Routes.users_session_path(@conn, :new) %>
</p>

lib/generic_web/templates/users_reset_password/new.html.eex
<h1>Forgot your password?</h1>

<%= form_for :users, Routes.users_reset_password_path(@conn, :create), fn f -> %>
  <%= label f, :email %>
  <%= text_input f, :email, required: true %>

  <div>
    <%= submit "Send instructions to reset password" %>
  </div>
<% end %>

<p>
  <%= link "Register", to: Routes.users_registration_path(@conn, :new) %> |
  <%= link "Login", to: Routes.users_session_path(@conn, :new) %>
</p>